System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build.js": [
      "app/main.js",
      "app/app.component.js",
      "npm:angular2@2.0.0-beta.17/core.js",
      "npm:angular2@2.0.0-beta.17/src/core/reflection/reflection.js",
      "npm:angular2@2.0.0-beta.17/src/core/reflection/reflection_capabilities.js",
      "npm:angular2@2.0.0-beta.17/src/facade/exceptions.js",
      "npm:angular2@2.0.0-beta.17/src/facade/exception_handler.js",
      "npm:angular2@2.0.0-beta.17/src/facade/collection.js",
      "npm:angular2@2.0.0-beta.17/src/facade/lang.js",
      "npm:angular2@2.0.0-beta.17/src/facade/base_wrapped_exception.js",
      "npm:angular2@2.0.0-beta.17/src/core/reflection/reflector.js",
      "npm:angular2@2.0.0-beta.17/src/core/reflection/reflector_reader.js",
      "npm:angular2@2.0.0-beta.17/src/core/application_common_providers.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/dynamic_component_loader.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/component_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/component_factory.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view_utils.js",
      "npm:angular2@2.0.0-beta.17/src/core/application_tokens.js",
      "npm:angular2@2.0.0-beta.17/src/core/di.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/opaque_token.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/reflective_exceptions.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/reflective_key.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/forward_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/reflective_provider.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/provider.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/metadata.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/reflective_injector.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/injector.js",
      "npm:angular2@2.0.0-beta.17/src/core/di/decorators.js",
      "npm:angular2@2.0.0-beta.17/src/core/util/decorators.js",
      "npm:angular2@2.0.0-beta.17/src/core/render/api.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/change_detection.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/change_detection_util.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/change_detector_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/constants.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/differs/default_keyvalue_differ.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/differs/keyvalue_differs.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/differs/default_iterable_differ.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection/differs/iterable_differs.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/exceptions.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/element.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view_container_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/profile/profile.js",
      "npm:angular2@2.0.0-beta.17/src/core/profile/wtf_impl.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/element_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view_type.js",
      "npm:angular2@2.0.0-beta.17/src/facade/async.js",
      "npm:rxjs@5.0.0-beta.6/Observable.js",
      "npm:rxjs@5.0.0-beta.6/util/toSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/symbol/rxSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/util/root.js",
      "npm:rxjs@5.0.0-beta.6/Subscriber.js",
      "npm:rxjs@5.0.0-beta.6/Observer.js",
      "npm:rxjs@5.0.0-beta.6/Subscription.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js",
      "npm:rxjs@5.0.0-beta.6/util/UnsubscriptionError.js",
      "npm:rxjs@5.0.0-beta.6/util/errorObject.js",
      "npm:rxjs@5.0.0-beta.6/util/tryCatch.js",
      "npm:rxjs@5.0.0-beta.6/util/isFunction.js",
      "npm:rxjs@5.0.0-beta.6/util/isObject.js",
      "npm:rxjs@5.0.0-beta.6/util/isArray.js",
      "npm:rxjs@5.0.0-beta.6/symbol/observable.js",
      "npm:rxjs@5.0.0-beta.6/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.6/observable/PromiseObservable.js",
      "npm:rxjs@5.0.0-beta.6/Subject.js",
      "npm:rxjs@5.0.0-beta.6/util/ObjectUnsubscribedError.js",
      "npm:rxjs@5.0.0-beta.6/util/throwError.js",
      "npm:rxjs@5.0.0-beta.6/SubjectSubscription.js",
      "npm:angular2@2.0.0-beta.17/src/facade/promise.js",
      "npm:angular2@2.0.0-beta.17/src/core/application_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/console.js",
      "npm:angular2@2.0.0-beta.17/src/core/testability/testability.js",
      "npm:angular2@2.0.0-beta.17/src/core/zone/ng_zone.js",
      "npm:angular2@2.0.0-beta.17/src/core/zone/ng_zone_impl.js",
      "npm:angular2@2.0.0-beta.17/src/core/platform_common_providers.js",
      "npm:angular2@2.0.0-beta.17/src/core/platform_directives_and_pipes.js",
      "npm:angular2@2.0.0-beta.17/src/core/change_detection.js",
      "npm:angular2@2.0.0-beta.17/src/core/debug/debug_node.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/template_ref.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/query_list.js",
      "npm:angular2@2.0.0-beta.17/src/core/render.js",
      "npm:angular2@2.0.0-beta.17/src/core/zone.js",
      "npm:angular2@2.0.0-beta.17/src/facade/facade.js",
      "npm:angular2@2.0.0-beta.17/src/core/prod_mode.js",
      "npm:angular2@2.0.0-beta.17/src/core/util.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata/view.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata/directives.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata/di.js",
      "npm:angular2@2.0.0-beta.17/platform/browser.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/xhr_impl.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/xhr.js",
      "npm:angular2@2.0.0-beta.17/compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/template_ast.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/expression_parser/lexer.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/expression_parser/parser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/expression_parser/ast.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/schema/dom_element_schema_registry.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/schema/element_schema_registry.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/html_tags.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/dom_adapter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/runtime_compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/interpretive_view.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/view.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/element_injector.js",
      "npm:angular2@2.0.0-beta.17/src/core/linker/debug_context.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/output_interpreter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/ts_emitter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/path_util.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/abstract_emitter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/output_ast.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/dart_emitter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/output_jit.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/util.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/output/abstract_js_emitter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/config.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/identifiers.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/compile_metadata.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/url_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/core/metadata/lifecycle_hooks.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/selector.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/runtime_metadata.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/assertions.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/directive_lifecycle_reflector.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/pipe_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/directive_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/directive_normalizer.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/template_preparser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/html_parser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/parse_util.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/html_lexer.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/html_ast.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/style_url_resolver.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/template_parser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/provider_parser.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/view_compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/view_binder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/lifecycle_binder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/constants.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/event_binder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_binding.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/expression_converter.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_method.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/property_binder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/view_builder.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/util.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_element.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_query.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_view.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/view_compiler/compile_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/style_compiler.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/shadow_css.js",
      "npm:angular2@2.0.0-beta.17/src/compiler/offline_compiler.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser_common.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/hammer_gestures.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/hammer_common.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/event_manager.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/tools/tools.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/tools/common_tools.js",
      "npm:angular2@2.0.0-beta.17/src/facade/browser.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/title.js",
      "npm:angular2@2.0.0-beta.17/platform/common_dom.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/debug/ng_probe.js",
      "npm:angular2@2.0.0-beta.17/src/core/debug/debug_renderer.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/dom_renderer.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/util.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/dom_tokens.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/shared_styles_host.js",
      "npm:angular2@2.0.0-beta.17/src/animate/animation_builder.js",
      "npm:angular2@2.0.0-beta.17/src/animate/browser_details.js",
      "npm:angular2@2.0.0-beta.17/src/facade/math.js",
      "npm:angular2@2.0.0-beta.17/src/animate/css_animation_builder.js",
      "npm:angular2@2.0.0-beta.17/src/animate/animation.js",
      "npm:angular2@2.0.0-beta.17/src/animate/css_animation_options.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/debug/by.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/dom_events.js",
      "npm:angular2@2.0.0-beta.17/src/core/profile/wtf_init.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/xhr_cache.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/testability.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/browser_adapter.js",
      "npm:angular2@2.0.0-beta.17/src/platform/browser/generic_browser_adapter.js",
      "npm:angular2@2.0.0-beta.17/src/platform/dom/events/key_events.js",
      "npm:angular2@2.0.0-beta.17/common.js",
      "npm:angular2@2.0.0-beta.17/src/common/common_directives.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/core_directives.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_plural.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_switch.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_style.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_template_outlet.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_if.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_for.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/ng_class.js",
      "npm:angular2@2.0.0-beta.17/src/common/directives/observable_list_diff.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/radio_control_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_control.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/abstract_control_directive.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/control_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/form_builder.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/model.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/validators.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/validators.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/select_control_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_control_status.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/number_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/checkbox_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/default_value_accessor.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_form.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/shared.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/normalize_validator.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/control_container.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_form_model.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_control_group.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_model.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_form_control.js",
      "npm:angular2@2.0.0-beta.17/src/common/forms/directives/ng_control_name.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/common_pipes.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/i18n_select_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/invalid_pipe_argument_exception.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/i18n_plural_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/replace_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/number_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/facade/intl.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/date_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/slice_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/json_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/lowercase_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/uppercase_pipe.js",
      "npm:angular2@2.0.0-beta.17/src/common/pipes/async_pipe.js",
      "npm:reflect-metadata@0.1.3.js",
      "npm:reflect-metadata@0.1.3/Reflect.js",
      "github:jspm/nodelibs-crypto@0.1.0.js",
      "github:jspm/nodelibs-crypto@0.1.0/index.js",
      "npm:crypto-browserify@3.11.0.js",
      "npm:crypto-browserify@3.11.0/index.js",
      "npm:public-encrypt@4.0.0.js",
      "npm:public-encrypt@4.0.0/browser.js",
      "npm:public-encrypt@4.0.0/privateDecrypt.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:public-encrypt@4.0.0/withPublic.js",
      "npm:bn.js@4.11.3.js",
      "npm:bn.js@4.11.3/lib/bn.js",
      "npm:create-hash@1.1.2.js",
      "npm:create-hash@1.1.2/browser.js",
      "npm:cipher-base@1.0.2.js",
      "npm:cipher-base@1.0.2/index.js",
      "github:jspm/nodelibs-string_decoder@0.1.0.js",
      "github:jspm/nodelibs-string_decoder@0.1.0/index.js",
      "npm:string_decoder@0.10.31.js",
      "npm:string_decoder@0.10.31/index.js",
      "npm:inherits@2.0.1.js",
      "npm:inherits@2.0.1/inherits_browser.js",
      "github:jspm/nodelibs-stream@0.1.0.js",
      "github:jspm/nodelibs-stream@0.1.0/index.js",
      "npm:stream-browserify@1.0.0.js",
      "npm:stream-browserify@1.0.0/index.js",
      "npm:readable-stream@1.1.14/passthrough.js",
      "npm:readable-stream@1.1.14/lib/_stream_passthrough.js",
      "npm:core-util-is@1.0.2.js",
      "npm:core-util-is@1.0.2/lib/util.js",
      "npm:readable-stream@1.1.14/lib/_stream_transform.js",
      "npm:readable-stream@1.1.14/lib/_stream_duplex.js",
      "npm:readable-stream@1.1.14/lib/_stream_writable.js",
      "npm:readable-stream@1.1.14/lib/_stream_readable.js",
      "github:jspm/nodelibs-events@0.1.1.js",
      "github:jspm/nodelibs-events@0.1.1/index.js",
      "npm:events@1.0.2.js",
      "npm:events@1.0.2/events.js",
      "npm:isarray@0.0.1.js",
      "npm:isarray@0.0.1/index.js",
      "npm:readable-stream@1.1.14/transform.js",
      "npm:readable-stream@1.1.14/duplex.js",
      "npm:readable-stream@1.1.14/writable.js",
      "npm:readable-stream@1.1.14/readable.js",
      "npm:sha.js@2.4.5.js",
      "npm:sha.js@2.4.5/index.js",
      "npm:sha.js@2.4.5/sha512.js",
      "npm:sha.js@2.4.5/hash.js",
      "npm:sha.js@2.4.5/sha384.js",
      "npm:sha.js@2.4.5/sha256.js",
      "npm:sha.js@2.4.5/sha224.js",
      "npm:sha.js@2.4.5/sha1.js",
      "npm:sha.js@2.4.5/sha.js",
      "npm:ripemd160@1.0.1.js",
      "npm:ripemd160@1.0.1/lib/ripemd160.js",
      "npm:create-hash@1.1.2/md5.js",
      "npm:create-hash@1.1.2/helpers.js",
      "npm:browserify-rsa@4.0.1.js",
      "npm:browserify-rsa@4.0.1/index.js",
      "npm:randombytes@2.0.3.js",
      "npm:randombytes@2.0.3/browser.js",
      "npm:public-encrypt@4.0.0/xor.js",
      "npm:public-encrypt@4.0.0/mgf.js",
      "npm:parse-asn1@5.0.0.js",
      "npm:parse-asn1@5.0.0/index.js",
      "npm:pbkdf2@3.0.4.js",
      "npm:pbkdf2@3.0.4/browser.js",
      "npm:create-hmac@1.1.4.js",
      "npm:create-hmac@1.1.4/browser.js",
      "npm:browserify-aes@1.0.6.js",
      "npm:browserify-aes@1.0.6/browser.js",
      "npm:browserify-aes@1.0.6/modes.js",
      "npm:browserify-aes@1.0.6/decrypter.js",
      "npm:browserify-aes@1.0.6/modes/ctr.js",
      "npm:buffer-xor@1.0.3.js",
      "npm:buffer-xor@1.0.3/index.js",
      "npm:browserify-aes@1.0.6/modes/ofb.js",
      "npm:browserify-aes@1.0.6/modes/cfb1.js",
      "npm:browserify-aes@1.0.6/modes/cfb8.js",
      "npm:browserify-aes@1.0.6/modes/cfb.js",
      "npm:browserify-aes@1.0.6/modes/cbc.js",
      "npm:browserify-aes@1.0.6/modes/ecb.js",
      "npm:evp_bytestokey@1.0.0.js",
      "npm:evp_bytestokey@1.0.0/index.js",
      "npm:browserify-aes@1.0.6/authCipher.js",
      "npm:browserify-aes@1.0.6/ghash.js",
      "npm:browserify-aes@1.0.6/aes.js",
      "npm:browserify-aes@1.0.6/streamCipher.js",
      "npm:browserify-aes@1.0.6/encrypter.js",
      "npm:parse-asn1@5.0.0/fixProc.js",
      "npm:parse-asn1@5.0.0/aesid.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:parse-asn1@5.0.0/asn1.js",
      "npm:asn1.js@4.6.0.js",
      "npm:asn1.js@4.6.0/lib/asn1.js",
      "npm:asn1.js@4.6.0/lib/asn1/encoders/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/encoders/pem.js",
      "npm:asn1.js@4.6.0/lib/asn1/encoders/der.js",
      "npm:asn1.js@4.6.0/lib/asn1/decoders/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/decoders/pem.js",
      "npm:asn1.js@4.6.0/lib/asn1/decoders/der.js",
      "npm:asn1.js@4.6.0/lib/asn1/constants/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/constants/der.js",
      "npm:asn1.js@4.6.0/lib/asn1/base/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/base/node.js",
      "npm:minimalistic-assert@1.0.0.js",
      "npm:minimalistic-assert@1.0.0/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/base/buffer.js",
      "npm:asn1.js@4.6.0/lib/asn1/base/reporter.js",
      "npm:asn1.js@4.6.0/lib/asn1/api.js",
      "github:jspm/nodelibs-vm@0.1.0.js",
      "github:jspm/nodelibs-vm@0.1.0/index.js",
      "npm:vm-browserify@0.0.4.js",
      "npm:vm-browserify@0.0.4/index.js",
      "npm:indexof@0.0.1.js",
      "npm:indexof@0.0.1/index.js",
      "npm:public-encrypt@4.0.0/publicEncrypt.js",
      "npm:create-ecdh@4.0.0.js",
      "npm:create-ecdh@4.0.0/browser.js",
      "npm:elliptic@6.2.3.js",
      "npm:elliptic@6.2.3/lib/elliptic.js",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/index.js",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/signature.js",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/key.js",
      "npm:hash.js@1.0.3.js",
      "npm:hash.js@1.0.3/lib/hash.js",
      "npm:hash.js@1.0.3/lib/hash/hmac.js",
      "npm:hash.js@1.0.3/lib/hash/ripemd.js",
      "npm:hash.js@1.0.3/lib/hash/sha.js",
      "npm:hash.js@1.0.3/lib/hash/common.js",
      "npm:hash.js@1.0.3/lib/hash/utils.js",
      "npm:elliptic@6.2.3/lib/elliptic/ec/index.js",
      "npm:elliptic@6.2.3/lib/elliptic/ec/signature.js",
      "npm:elliptic@6.2.3/lib/elliptic/ec/key.js",
      "npm:elliptic@6.2.3/lib/elliptic/curves.js",
      "npm:elliptic@6.2.3/lib/elliptic/precomputed/secp256k1.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/index.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/edwards.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/mont.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/short.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/base.js",
      "npm:elliptic@6.2.3/lib/elliptic/hmac-drbg.js",
      "npm:brorand@1.0.5.js",
      "npm:brorand@1.0.5/index.js",
      "npm:elliptic@6.2.3/lib/elliptic/utils.js",
      "npm:elliptic@6.2.3/package.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-sign@4.0.0.js",
      "npm:browserify-sign@4.0.0/browser.js",
      "npm:browserify-sign@4.0.0/verify.js",
      "npm:browserify-sign@4.0.0/curves.js",
      "npm:browserify-sign@4.0.0/sign.js",
      "npm:browserify-sign@4.0.0/algos.js",
      "npm:diffie-hellman@5.0.2.js",
      "npm:diffie-hellman@5.0.2/browser.js",
      "npm:diffie-hellman@5.0.2/lib/dh.js",
      "npm:diffie-hellman@5.0.2/lib/generatePrime.js",
      "npm:miller-rabin@4.0.0.js",
      "npm:miller-rabin@4.0.0/lib/mr.js",
      "npm:diffie-hellman@5.0.2/lib/primes.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-cipher@1.0.0.js",
      "npm:browserify-cipher@1.0.0/browser.js",
      "npm:browserify-des@1.0.0/modes.js",
      "npm:browserify-des@1.0.0.js",
      "npm:browserify-des@1.0.0/index.js",
      "npm:des.js@1.0.0.js",
      "npm:des.js@1.0.0/lib/des.js",
      "npm:des.js@1.0.0/lib/des/ede.js",
      "npm:des.js@1.0.0/lib/des/cbc.js",
      "npm:des.js@1.0.0/lib/des/des.js",
      "npm:des.js@1.0.0/lib/des/cipher.js",
      "npm:des.js@1.0.0/lib/des/utils.js",
      "npm:zone.js@0.6.12.js",
      "npm:zone.js@0.6.12/dist/zone.js"
    ]
  },

  packages: {
    "app": {
      "main": "main",
      "format": "register",
      "defaultExtension": "js"
    }
  },

  map: {
    "angular2": "npm:angular2@2.0.0-beta.17",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "core-js": "npm:core-js@1.2.6",
    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
    "cryptojs": "github:sytelus/cryptojs@3.1.2",
    "es6-shim": "github:es-shims/es6-shim@0.35.0",
    "reflect-metadata": "npm:reflect-metadata@0.1.3",
    "rxjs": "npm:rxjs@5.0.0-beta.6",
    "systemjs": "npm:systemjs@0.19.27",
    "zone.js": "npm:zone.js@0.6.12",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:angular2@2.0.0-beta.17": {
      "reflect-metadata": "npm:reflect-metadata@0.1.2",
      "rxjs": "npm:rxjs@5.0.0-beta.6",
      "zone.js": "npm:zone.js@0.6.12"
    },
    "npm:asn1.js@4.6.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bn.js@4.11.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.5"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:elliptic@6.2.3": {
      "bn.js": "npm:bn.js@4.11.3",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.6.0",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:randombytes@2.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:reflect-metadata@0.1.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:rxjs@5.0.0-beta.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:systemjs@0.19.27": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "when": "npm:when@3.7.7"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:when@3.7.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:zone.js@0.6.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
